//! Terminal UI dashboard for monitoring the AI Core Router.
//!
//! Feature-gated behind `tui` feature flag. Uses ratatui + crossterm.
//! Visual design closely mirrors hai-cli's Go TUI (tview + tcell).

use std::collections::VecDeque;
use std::io;
use std::time::Duration;

use crossterm::{
    event::{
        self, DisableMouseCapture, EnableMouseCapture, Event, KeyCode, KeyEventKind, MouseEventKind,
    },
    execute,
    terminal::{EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode, enable_raw_mode},
};
use ratatui::{
    Frame, Terminal,
    backend::CrosstermBackend,
    layout::{Alignment, Constraint, Direction, Layout},
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Cell, Padding, Paragraph, Row, Table, Wrap},
};
use tokio::sync::mpsc;
use tracing::Level;

use crate::metrics::MetricsService;
use crate::quota::QuotaManager;
use crate::registry::ModelRegistry;

// ── Theme ────────────────────────────────────────────────────────────
// RGB palette matching hai-cli's dark theme with cyan/teal accents.

mod theme {
    use ratatui::style::Color;

    // Backgrounds
    pub const BACKGROUND: Color = Color::Rgb(18, 18, 24);
    pub const SURFACE: Color = Color::Rgb(38, 38, 52);
    pub const HEADER_BG: Color = Color::Rgb(25, 25, 35);

    // Text
    pub const TEXT_PRIMARY: Color = Color::Rgb(240, 240, 245);
    pub const TEXT_SECONDARY: Color = Color::Rgb(180, 180, 195);
    pub const TEXT_MUTED: Color = Color::Rgb(120, 120, 140);

    // Accents
    pub const ACCENT: Color = Color::Rgb(0, 188, 212);
    pub const ACCENT_BRIGHT: Color = Color::Rgb(77, 208, 225);
    pub const SUCCESS: Color = Color::Rgb(76, 175, 80);
    pub const WARNING: Color = Color::Rgb(255, 193, 7);
    pub const ERROR: Color = Color::Rgb(244, 67, 54);

    // Borders
    pub const BORDER: Color = Color::Rgb(60, 60, 80);

    // Log-specific (softer variants)
    pub const LOG_ERROR: Color = Color::Rgb(255, 107, 107);
    pub const LOG_WARN: Color = Color::Rgb(255, 179, 71);
    pub const LOG_DEBUG: Color = Color::Rgb(136, 136, 136);
}

// ── Layout constants ────────────────────────────────────────────────
/// Horizontal margin (columns) applied to stats, logs, and footer sections.
const HORIZONTAL_MARGIN: u16 = 2;
/// Total horizontal space consumed by log widget chrome (margins + borders + padding).
const LOG_HORIZONTAL_CHROME: u16 = HORIZONTAL_MARGIN * 2 + 2 + 2; // margins + borders + padding
/// Total vertical space consumed by non-log sections (header + stats + spacer + footer + log borders + padding).
const FIXED_VERTICAL_ROWS: u16 = 13;

/// Color for quota percentage: green (0-59%), yellow (60-84%), red (85-100%).
fn quota_color(percentage: f64) -> Color {
    if percentage >= 85.0 {
        theme::ERROR
    } else if percentage >= 60.0 {
        theme::WARNING
    } else {
        theme::SUCCESS
    }
}

// ── Tips ─────────────────────────────────────────────────────────────

const TIPS: &[&str] = &[
    "Tokens Out = output tokens generated by the model",
    "Tokens In = input tokens freshly processed (excludes cached)",
    "Cache W = tokens written to cache (first-time cache creation)",
    "Cache R = tokens read from cache (cheap, avoids reprocessing)",
    "Total input = In + Cache W + Cache R (billed at different rates)",
    "Cache write is only reported for Claude; OpenAI/Gemini report reads only",
    "Quotas count all tokens equally: In + Out + Cache R + Cache W",
    "Claude: output tokens cost 3-5x more than input tokens",
    "Claude: cache reads cost ~10% of normal input price",
    "Claude: cache creation costs ~25% more than normal input",
    "OpenAI: cached tokens are free — no extra charge for cache hits",
    "Gemini: cached content reduces input cost by ~75%",
    "Claude output includes thinking tokens (extended thinking mode)",
    "Gemini output = candidatesTokenCount + thoughtsTokenCount",
    "OpenAI reasoning_tokens count toward completion_tokens (full price)",
    "Model suffix [1m] enables extended context (acr injects beta header)",
    "429 from upstream = provider rate limited, acr tries next provider",
    "Quota resets: daily at local midnight, monthly on the 1st",
    "Set per-key daily_token_limit: 0 for unlimited (overrides global)",
    "Tab / Shift+Tab to cycle through API keys",
    "Quota \"--\" means unlimited (no limit configured for that period)",
    "Model aliases allow variant names (e.g. claude-sonnet-4-6-20260101) to route to configured models",
    "Unknown model falls back to configured default for that family (claude/openai/gemini)",
    #[cfg(feature = "db")]
    "Run 'acr usage' to see historical per-key token usage from the database",
    #[cfg(not(feature = "db"))]
    "Quota* = in-memory only (resets on restart, no persistence without 'db' feature)",
];

// ── Proxy status ─────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProxyStatus {
    Starting,
    Ready,
    Active,
    Error,
}

impl ProxyStatus {
    fn icon(&self) -> &'static str {
        match self {
            Self::Starting => "\u{23f3}", // ⏳
            Self::Ready => "\u{1f7e2}",   // 🟢
            Self::Active => "\u{26a1}",   // ⚡
            Self::Error => "\u{1f534}",   // 🔴
        }
    }

    fn label(&self) -> &'static str {
        match self {
            Self::Starting => "Starting...",
            Self::Ready => "Ready",
            Self::Active => "Forwarding",
            Self::Error => "Error",
        }
    }

    fn color(&self) -> Color {
        match self {
            Self::Starting => theme::WARNING,
            Self::Ready => theme::SUCCESS,
            Self::Active => theme::WARNING,
            Self::Error => theme::ERROR,
        }
    }
}

// ── Log entry ────────────────────────────────────────────────────────

/// A log entry captured from the tracing system.
#[derive(Debug, Clone)]
pub struct LogEntry {
    pub timestamp: String,
    pub level: Level,
    pub message: String,
}

// ── TUI application ─────────────────────────────────────────────────

/// TUI application state.
pub struct TuiApp {
    proxy_url: String,
    api_keys: Vec<String>,
    selected_key_index: usize,
    quota_manager: Option<QuotaManager>,
    model_registry: ModelRegistry,
    models: Vec<crate::config::Model>,
    metrics: MetricsService,
    log_rx: mpsc::Receiver<LogEntry>,
    log_buffer: VecDeque<LogEntry>,
    scroll_y: u16,
    max_scroll: u16,
    max_log_entries: usize,
    auto_scroll: bool,
    started: bool,
    tip_index: usize,
    last_tip_rotation: std::time::Instant,
}

impl TuiApp {
    pub fn new(
        proxy_url: String,
        api_keys: Vec<String>,
        quota_manager: Option<QuotaManager>,
        model_registry: ModelRegistry,
        models: Vec<crate::config::Model>,
        metrics: MetricsService,
        log_rx: mpsc::Receiver<LogEntry>,
    ) -> Self {
        Self {
            proxy_url,
            api_keys,
            selected_key_index: 0,
            quota_manager,
            model_registry,
            models,
            metrics,
            log_rx,
            log_buffer: VecDeque::new(),
            scroll_y: 0,
            max_scroll: 0,
            max_log_entries: 1000,
            auto_scroll: true,
            started: false,
            tip_index: 0,
            last_tip_rotation: std::time::Instant::now(),
        }
    }

    /// Compute the total number of visual (wrapped) lines for all log entries.
    fn compute_total_visual_lines(&self, content_width: u16) -> u16 {
        if content_width == 0 || self.log_buffer.is_empty() {
            return 0;
        }
        let lines: Vec<Line> = self
            .log_buffer
            .iter()
            .map(|entry| self.format_log_line(entry))
            .collect();
        let paragraph = Paragraph::new(lines).wrap(Wrap { trim: true });
        paragraph.line_count(content_width) as u16
    }

    /// Format a single log entry into a styled Line.
    fn format_log_line<'a>(&self, entry: &'a LogEntry) -> Line<'a> {
        let level_color = match entry.level {
            Level::ERROR => theme::LOG_ERROR,
            Level::WARN => theme::LOG_WARN,
            Level::INFO => theme::TEXT_SECONDARY,
            Level::DEBUG | Level::TRACE => theme::LOG_DEBUG,
        };
        Line::from(vec![
            Span::styled(
                format!("{} ", entry.timestamp),
                Style::default().fg(theme::TEXT_MUTED).bg(theme::BACKGROUND),
            ),
            Span::styled(
                format!("{:<5} ", entry.level),
                Style::default().fg(level_color).bg(theme::BACKGROUND),
            ),
            Span::styled(
                entry.message.clone(),
                Style::default()
                    .fg(theme::TEXT_PRIMARY)
                    .bg(theme::BACKGROUND),
            ),
        ])
    }

    pub fn run(&mut self) -> io::Result<()> {
        enable_raw_mode()?;
        let mut stdout = io::stdout();
        execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;
        let backend = CrosstermBackend::new(stdout);
        let mut terminal = Terminal::new(backend)?;

        let result = self.run_loop(&mut terminal);

        // Restore terminal state, even if the loop errored.
        //
        // Order matters: `DisableMouseCapture` and `LeaveAlternateScreen` must
        // be sent while raw mode is still on, so the escape sequences are
        // processed as escapes by the terminal rather than echoed as input.
        // After that, drain any in-flight events the terminal queued during
        // shutdown (motion events from mode 1003 are the usual culprit — they
        // arrive as `65;<col>;<row>M` strings if not consumed before
        // `disable_raw_mode` flushes the input buffer back to the shell).
        let _ = execute!(
            terminal.backend_mut(),
            DisableMouseCapture,
            LeaveAlternateScreen
        );
        while event::poll(Duration::ZERO).unwrap_or(false) {
            let _ = event::read();
        }
        let _ = disable_raw_mode();
        let _ = terminal.show_cursor();

        result
    }

    fn run_loop(
        &mut self,
        terminal: &mut Terminal<CrosstermBackend<io::Stdout>>,
    ) -> io::Result<()> {
        loop {
            // Drain log messages
            let mut new_logs = false;
            while let Ok(entry) = self.log_rx.try_recv() {
                new_logs = true;
                self.log_buffer.push_back(entry);
                if self.log_buffer.len() > self.max_log_entries {
                    self.log_buffer.pop_front();
                }
            }

            // Mark as started after first log arrives
            if !self.started && !self.log_buffer.is_empty() {
                self.started = true;
            }

            // Auto-rotate tips every 5 seconds
            if self.last_tip_rotation.elapsed() >= Duration::from_secs(5) {
                self.tip_index = (self.tip_index + 1) % TIPS.len();
                self.last_tip_rotation = std::time::Instant::now();
            }

            // Compute scroll bounds based on current terminal size.
            // Log content width = terminal width - 2*margin - 2*border
            let size = terminal.size()?;
            let content_width = size.width.saturating_sub(LOG_HORIZONTAL_CHROME);
            let viewport_height = size.height.saturating_sub(FIXED_VERTICAL_ROWS);
            let total_visual = self.compute_total_visual_lines(content_width);
            self.max_scroll = total_visual.saturating_sub(viewport_height);

            // Auto-scroll to bottom when new logs arrive
            if new_logs && self.auto_scroll {
                self.scroll_y = self.max_scroll;
            }

            // Clamp scroll_y after resize or buffer eviction
            if self.scroll_y > self.max_scroll {
                self.scroll_y = self.max_scroll;
            }

            terminal.draw(|f| self.render(f))?;

            // Poll for keyboard/mouse events with timeout
            if event::poll(Duration::from_millis(100))? {
                match event::read()? {
                    Event::Key(key) if key.kind == KeyEventKind::Press => match key.code {
                        KeyCode::Char('q') | KeyCode::Esc => break,
                        KeyCode::Char('?') => {
                            self.tip_index = (self.tip_index + 1) % TIPS.len();
                            self.last_tip_rotation = std::time::Instant::now();
                        }
                        // Scroll up
                        KeyCode::Up | KeyCode::Char('k') => {
                            self.auto_scroll = false;
                            self.scroll_y = self.scroll_y.saturating_sub(1);
                        }
                        // Scroll down
                        KeyCode::Down | KeyCode::Char('j') => {
                            self.scroll_y = (self.scroll_y + 1).min(self.max_scroll);
                            if self.scroll_y == self.max_scroll {
                                self.auto_scroll = true;
                            }
                        }
                        // Jump to top
                        KeyCode::Home | KeyCode::Char('g') => {
                            self.auto_scroll = false;
                            self.scroll_y = 0;
                        }
                        // Jump to bottom
                        KeyCode::End | KeyCode::Char('G') => {
                            self.scroll_y = self.max_scroll;
                            self.auto_scroll = true;
                        }
                        // Cycle API keys
                        KeyCode::Tab => {
                            self.selected_key_index =
                                (self.selected_key_index + 1) % self.api_keys.len().max(1);
                        }
                        KeyCode::BackTab => {
                            if self.selected_key_index == 0 {
                                self.selected_key_index = self.api_keys.len().saturating_sub(1);
                            } else {
                                self.selected_key_index -= 1;
                            }
                        }
                        _ => {}
                    },
                    Event::Mouse(mouse) => match mouse.kind {
                        MouseEventKind::ScrollUp => {
                            self.auto_scroll = false;
                            self.scroll_y = self.scroll_y.saturating_sub(3);
                        }
                        MouseEventKind::ScrollDown => {
                            self.scroll_y = (self.scroll_y + 3).min(self.max_scroll);
                            if self.scroll_y == self.max_scroll {
                                self.auto_scroll = true;
                            }
                        }
                        _ => {}
                    },
                    _ => {}
                }
            }
        }

        Ok(())
    }

    // ── Layout ───────────────────────────────────────────────────────

    fn render(&self, frame: &mut Frame) {
        // Fill the whole screen with the background color
        let bg_block = Block::default().style(Style::default().bg(theme::BACKGROUND));
        frame.render_widget(bg_block, frame.area());

        // Full-width vertical layout
        let full_chunks = Layout::default()
            .direction(Direction::Vertical)
            .constraints([
                Constraint::Length(3), // Header (full width)
                Constraint::Length(6), // Stats table (full width)
                Constraint::Length(1), // Spacer
                Constraint::Min(5),    // Log viewer (with margin)
                Constraint::Length(1), // Footer (with margin)
            ])
            .split(frame.area());

        // Header renders full-width (no margin)
        self.render_header(frame, full_chunks[0]);

        // Stats: background full-width, but bordered box inset with margin
        let stats_bg = Block::default().style(Style::default().bg(theme::SURFACE));
        frame.render_widget(stats_bg, full_chunks[1]);
        let stats_outer = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([
                Constraint::Length(HORIZONTAL_MARGIN),
                Constraint::Fill(1),
                Constraint::Length(HORIZONTAL_MARGIN),
            ])
            .split(full_chunks[1]);
        self.render_stats(frame, stats_outer[1]);

        // Log viewer and footer get horizontal margin
        let log_outer = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([
                Constraint::Length(HORIZONTAL_MARGIN),
                Constraint::Fill(1),
                Constraint::Length(HORIZONTAL_MARGIN),
            ])
            .split(full_chunks[3]);
        self.render_logs(frame, log_outer[1]);

        let footer_outer = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([
                Constraint::Length(HORIZONTAL_MARGIN),
                Constraint::Fill(1),
                Constraint::Length(HORIZONTAL_MARGIN),
            ])
            .split(full_chunks[4]);
        self.render_footer(frame, footer_outer[1]);
    }

    // ── Header ───────────────────────────────────────────────────────

    fn render_header(&self, frame: &mut Frame, area: ratatui::layout::Rect) {
        let lines = vec![
            Line::from(""),
            Line::from(Span::styled(
                "\u{1f680} AI Core Router - LLM API Proxy",
                Style::default()
                    .fg(theme::ACCENT)
                    .add_modifier(Modifier::BOLD),
            )),
            Line::from(Span::styled(
                format!("Version: {}", env!("CARGO_PKG_VERSION")),
                Style::default()
                    .fg(theme::ACCENT)
                    .add_modifier(Modifier::DIM),
            )),
        ];

        let block = Block::default().style(Style::default().bg(theme::HEADER_BG));
        let paragraph = Paragraph::new(lines)
            .block(block)
            .alignment(Alignment::Center);
        frame.render_widget(paragraph, area);
    }

    // ── Stats table ──────────────────────────────────────────────────

    fn render_stats(&self, frame: &mut Frame, area: ratatui::layout::Rect) {
        let snap = self.metrics.snapshot_sync();

        let status = if !self.started {
            ProxyStatus::Starting
        } else if self.model_registry.resolved_model_count_sync() == Some(0) {
            ProxyStatus::Error
        } else if snap.active_requests > 0 {
            ProxyStatus::Active
        } else {
            ProxyStatus::Ready
        };

        let status_text = format!("{} {}", status.icon(), status.label());

        let label = |s: &str| -> Cell<'_> {
            Cell::from(format!(" {s}: ")).style(
                Style::default()
                    .fg(theme::TEXT_SECONDARY)
                    .bg(theme::SURFACE),
            )
        };

        let value = |s: String| -> Cell<'_> {
            Cell::from(format!(" {s} ")).style(
                Style::default()
                    .fg(theme::ACCENT_BRIGHT)
                    .bg(theme::SURFACE)
                    .add_modifier(Modifier::BOLD),
            )
        };

        let status_cell = Cell::from(format!(" {status_text} ")).style(
            Style::default()
                .fg(status.color())
                .bg(theme::SURFACE)
                .add_modifier(Modifier::BOLD),
        );

        // Row 3: API Key with cycling indicator
        let key_label = if self.api_keys.len() > 1 {
            format!(
                "Key ({}/{})",
                self.selected_key_index + 1,
                self.api_keys.len()
            )
        } else {
            "API Key".to_string()
        };
        let key_value = self
            .api_keys
            .get(self.selected_key_index)
            .cloned()
            .unwrap_or_else(|| "N/A".to_string());

        // Row 3 c2: Requests with symbols
        let requests_display = format!("{} / {}", snap.successful_requests, snap.failed_requests);

        // Row 4: Quota display + Est. Cost
        let quota_display = self.render_quota_display();
        let cost_display = self.render_cost_display();

        let rows = vec![
            Row::new(vec![
                label("Status"),
                status_cell,
                label("Tokens (In/Out)"),
                value(format!(
                    "{} | {}",
                    snap.usage.total_input_tokens, snap.usage.total_output_tokens
                )),
            ]),
            Row::new(vec![
                label("Proxy URL"),
                value(self.proxy_url.clone()),
                label("Cache (R/W)"),
                value(format!(
                    "{} | {}",
                    snap.usage.total_cache_read_tokens, snap.usage.total_cache_write_tokens
                )),
            ]),
            Row::new(vec![
                label(&key_label),
                value(key_value),
                label("Requests (\u{2713}/\u{2717})"),
                value(requests_display),
            ]),
            Row::new(vec![
                label("Quota (D/M)"),
                quota_display,
                label("Est. Cost"),
                cost_display,
            ]),
        ];

        let widths = [
            Constraint::Length(16),
            Constraint::Fill(1),
            Constraint::Length(18),
            Constraint::Fill(1),
        ];

        let table = Table::new(rows, widths)
            .block(
                Block::default()
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(theme::BORDER))
                    .title(" \u{1f4ca} Information ")
                    .title_style(Style::default().fg(theme::ACCENT))
                    .style(Style::default().bg(theme::SURFACE)),
            )
            .style(Style::default().bg(theme::SURFACE));

        frame.render_widget(table, area);
    }

    /// Render quota usage as a colored cell showing daily% / monthly%.
    fn render_quota_display(&self) -> Cell<'_> {
        let Some(ref qm) = self.quota_manager else {
            return Cell::from(" -- / -- ").style(
                Style::default()
                    .fg(theme::TEXT_SECONDARY)
                    .bg(theme::SURFACE),
            );
        };

        let Some(key) = self.api_keys.get(self.selected_key_index) else {
            return Cell::from(" N/A ").style(
                Style::default()
                    .fg(theme::TEXT_SECONDARY)
                    .bg(theme::SURFACE),
            );
        };

        let Some(result) = qm.check_quota_sync(key) else {
            return Cell::from(" ... ").style(
                Style::default()
                    .fg(theme::TEXT_SECONDARY)
                    .bg(theme::SURFACE),
            );
        };

        use crate::quota::QuotaCheckResult;
        match result {
            QuotaCheckResult::Allowed {
                daily_remaining,
                monthly_remaining,
                daily_limit,
                monthly_limit,
                ..
            } => {
                let daily_pct = match (daily_remaining, daily_limit) {
                    (Some(remaining), Some(limit)) if limit > 0 => {
                        Some(((limit - remaining) as f64 / limit as f64) * 100.0)
                    }
                    _ => None,
                };
                let monthly_pct = match (monthly_remaining, monthly_limit) {
                    (Some(remaining), Some(limit)) if limit > 0 => {
                        Some(((limit - remaining) as f64 / limit as f64) * 100.0)
                    }
                    _ => None,
                };

                let daily_str = daily_pct
                    .map(|p| format!("{:.0}%", p))
                    .unwrap_or_else(|| "--".to_string());
                let monthly_str = monthly_pct
                    .map(|p| format!("{:.0}%", p))
                    .unwrap_or_else(|| "--".to_string());

                // Append * when db feature is off (no persistence)
                #[cfg(feature = "db")]
                let suffix = "";
                #[cfg(not(feature = "db"))]
                let suffix = "*";

                // Use the higher percentage for color
                let max_pct = daily_pct.unwrap_or(0.0).max(monthly_pct.unwrap_or(0.0));
                let color = quota_color(max_pct);

                Cell::from(format!(" {} / {}{} ", daily_str, monthly_str, suffix)).style(
                    Style::default()
                        .fg(color)
                        .bg(theme::SURFACE)
                        .add_modifier(Modifier::BOLD),
                )
            }
            QuotaCheckResult::Exceeded { limit_type, .. } => {
                Cell::from(format!(" EXCEEDED ({}) ", limit_type)).style(
                    Style::default()
                        .fg(Color::Red)
                        .bg(theme::SURFACE)
                        .add_modifier(Modifier::BOLD),
                )
            }
        }
    }

    /// Render estimated session cost from per-model usage and pricing config.
    fn render_cost_display(&self) -> Cell<'_> {
        let model_usage = match self.metrics.session_usage_by_model_sync() {
            Some(usage) if !usage.is_empty() => usage,
            _ => {
                return Cell::from(" N/A ").style(
                    Style::default()
                        .fg(theme::TEXT_SECONDARY)
                        .bg(theme::SURFACE),
                );
            }
        };

        let mut total_cost = 0.0;
        let mut any_priced = false;
        let mut any_partial = false;

        for (model_name, counts) in &model_usage {
            let pricing = self
                .models
                .iter()
                .find(|m| m.name == *model_name)
                .and_then(|m| m.pricing.as_ref());

            if let Some(p) = pricing {
                any_priced = true;
                total_cost += p.calculate_cost(counts);
                if p.is_partial(counts) {
                    any_partial = true;
                }
            }
        }

        if !any_priced {
            return Cell::from(" N/A ").style(
                Style::default()
                    .fg(theme::TEXT_SECONDARY)
                    .bg(theme::SURFACE),
            );
        }

        let cost_str = crate::format_cost_value(total_cost);

        if any_partial {
            Cell::from(format!(" {}* (partial) ", cost_str)).style(
                Style::default()
                    .fg(theme::WARNING)
                    .bg(theme::SURFACE)
                    .add_modifier(Modifier::BOLD),
            )
        } else {
            Cell::from(format!(" {} ", cost_str)).style(
                Style::default()
                    .fg(theme::ACCENT_BRIGHT)
                    .bg(theme::SURFACE)
                    .add_modifier(Modifier::BOLD),
            )
        }
    }

    // ── Log viewer ───────────────────────────────────────────────────

    fn render_logs(&self, frame: &mut Frame, area: ratatui::layout::Rect) {
        let total = self.log_buffer.len();
        let lines: Vec<Line> = self
            .log_buffer
            .iter()
            .map(|entry| self.format_log_line(entry))
            .collect();

        let title = format!(" \u{1f4cb} Proxy Logs ({total} entries) ");
        let block = Block::default()
            .borders(Borders::ALL)
            .border_style(Style::default().fg(theme::BORDER))
            .title(title)
            .title_style(Style::default().fg(theme::ACCENT))
            .padding(Padding::horizontal(1))
            .style(Style::default().bg(theme::BACKGROUND));

        let paragraph = Paragraph::new(lines)
            .block(block)
            .wrap(Wrap { trim: true })
            .scroll((self.scroll_y, 0));
        frame.render_widget(paragraph, area);
    }

    // ── Footer ───────────────────────────────────────────────────────

    fn render_footer(&self, frame: &mut Frame, area: ratatui::layout::Rect) {
        let tip = TIPS[self.tip_index];

        let footer_layout = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([Constraint::Fill(1), Constraint::Length(58)])
            .split(area);

        // Left: rolling tip
        let tip_line = Line::from(vec![
            Span::styled(" \u{1f4a1} ", Style::default().fg(theme::WARNING)),
            Span::styled(tip, Style::default().fg(theme::TEXT_SECONDARY)),
        ]);
        let tip_block = Block::default().style(Style::default().bg(theme::BACKGROUND));
        let tip_para = Paragraph::new(tip_line).block(tip_block);
        frame.render_widget(tip_para, footer_layout[0]);

        // Right: key hints
        let keys_line = Line::from(Span::styled(
            "? next tip \u{00b7} g/G - top/bottom \u{00b7} j/k - up/down \u{00b7} q - quit ",
            Style::default().fg(theme::TEXT_MUTED),
        ));
        let keys_block = Block::default().style(Style::default().bg(theme::BACKGROUND));
        let keys_para = Paragraph::new(keys_line)
            .block(keys_block)
            .alignment(Alignment::Right);
        frame.render_widget(keys_para, footer_layout[1]);
    }
}

// ── Tracing layer ────────────────────────────────────────────────────

/// Custom tracing layer that sends log entries to the TUI.
pub struct TuiLogLayer {
    sender: mpsc::Sender<LogEntry>,
}

impl TuiLogLayer {
    pub fn new(sender: mpsc::Sender<LogEntry>) -> Self {
        Self { sender }
    }
}

impl<S> tracing_subscriber::Layer<S> for TuiLogLayer
where
    S: tracing::Subscriber,
{
    fn on_event(
        &self,
        event: &tracing::Event<'_>,
        _ctx: tracing_subscriber::layer::Context<'_, S>,
    ) {
        let mut visitor = MessageVisitor::default();
        event.record(&mut visitor);

        let entry = LogEntry {
            timestamp: chrono::Local::now().format("%H:%M:%S").to_string(),
            level: *event.metadata().level(),
            message: visitor.message,
        };

        // Non-blocking send — drop if channel is full
        let _ = self.sender.try_send(entry);
    }
}

#[derive(Default)]
struct MessageVisitor {
    message: String,
}

impl tracing::field::Visit for MessageVisitor {
    fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
        if field.name() == "message" {
            self.message = format!("{:?}", value);
        } else if self.message.is_empty() {
            self.message = format!("{} = {:?}", field.name(), value);
        } else {
            self.message
                .push_str(&format!(", {} = {:?}", field.name(), value));
        }
    }

    fn record_str(&mut self, field: &tracing::field::Field, value: &str) {
        if field.name() == "message" {
            self.message = value.to_string();
        } else if self.message.is_empty() {
            self.message = format!("{} = {}", field.name(), value);
        } else {
            self.message
                .push_str(&format!(", {} = {}", field.name(), value));
        }
    }
}
